Repository CodeForAfrica/Dominion.AFRICA, pull requests merged in 2019-09, with the labels that each got.

#22 Fix console warnings
  src/components/About/Info.js
  src/components/CountryPartners/index.js
  src/components/Header/Header.js
  src/components/Header/Navigation.js
  src/components/Hero/Hero.js
  src/components/Hero/ProfileHero/Profile.js
  src/components/Hero/TitleHero.js
  src/components/Modal/ContactUs.js
  src/components/Modal/PortalChooser.js
  src/components/Modal/index.js
  src/components/ProfileReleases/index.js
  src/components/ProfileTabs.js
  src/components/Search/SearchResults.js
  src/components/Search/index.js
  src/pages/Profile.js
  src/pages/Resources.js
Labels: bug

#26 Add GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#24 Fix fonts and style
  public/index.html
  src/pages/Profile.js
Labels: bug

#25 Improve Profile Tabs
  src/components/ProfileTabs.js
Labels: enhancement

#29 Update Profile Section Title Design
  src/components/ProfileSectionTitle.js
Labels: enhancement

#31 Embed Page
  README.md
  package.json
  scripts/chartsDefinitionsApplyUniqueId.js
  src/App.js
  src/components/ChartFactory.js
  src/components/Hero/ProfileHero/Profile.js
  src/components/Hero/ProfileHero/index.js
  src/data/charts.json
  src/data/queries.js
  src/data/useChartDefinitions.js
  src/data/useProfileLoader.js
  src/pages/Embed.js
  src/pages/Profile.js
  yarn.lock
Labels: dependencies, documentation, enhancement

#32 Add Error pages
  src/App.js
  src/components/About/AboutCountry.js
  src/components/ErrorContent.js
  src/pages/Country.js
  src/pages/NotFound.js
  src/pages/ServerError.js
Labels: enhancement

#34 Use config supported countries
  src/App.js
  src/components/ProfileSectionTitle.js
  src/pages/Profile.js
Labels: enhancement

#33 Improve Use of Theme
  package.json
  src/Theme.js
  src/components/ChartFactory.js
  src/config.js
  src/data/charts.json
  src/pages/Profile.js
  yarn.lock
Labels: dependencies, enhancement

#35 [Hotfix] Fix iframe showcase story link
  src/config.js
Labels: bug

#40 Fix logo country name wrapping
  src/components/Header/Navigation.js
  src/pages/Profile.js
Labels: bug

#38 Show percent for charts claiming percent data
  src/components/ChartFactory.js
  src/data/charts.json
  src/utils/aggregateData.js
Labels: bug

#44 Fix alignment `geoLevel In countryName`
  src/components/Hero/ProfileHero/Profile.js
Labels: bug

#43 Fix many warnings and errors
  src/components/ChartFactory.js
  src/components/Hero/Hero.js
  src/components/Hero/ProfileHero/Profile.js
  src/components/Hero/ProfileHero/index.js
  src/components/ProfileSectionTitle.js
  src/data/useProfileLoader.js
  src/lib/api.js
  src/pages/Profile.js
Labels: bug

#45 Fix commitChartDefinition when nothing has been staged
  package.json
Labels: bug

#46 Format NumbersVisual numbers & Fix rounding
  src/components/ChartFactory.js
Labels: bug, enhancement

#42 Improve mobile responsive of the site
  src/Theme.js
  src/components/About/AboutCountry.js
  src/components/About/AboutDominion.js
  src/components/About/Header.js
  src/components/About/Info.js
  src/components/About/Land.js
  src/components/ArrowButton.js
  src/components/Card/Data.js
  src/components/Card/Document.js
  src/components/CountryPartners/PartnerContent.js
  src/components/CountryPartners/index.js
  src/components/Data/Content.js
  src/components/Data/DatasetsContent.js
  src/components/Data/DocumentsContents.js
  src/components/Data/index.js
  src/components/Footer/About.js
  src/components/Footer/Community.js
  src/components/Footer/Project.js
  src/components/Footer/index.js
  src/components/Header/Header.js
  src/components/Header/Navigation.js
  src/components/Hero/CountryHero.js
  src/components/Hero/Hero.js
  src/components/Hero/HomeHero.js
  src/components/Hero/HomeHeroMap.js
  src/components/Hero/ProfileHero/Profile.js
  src/components/Hero/TitleHero.js
  src/components/Modal/ContactUs.js
  src/components/Modal/PortalChooser.js
  src/components/Modal/index.js
  src/components/Partners.js
  src/components/ProfileReleases/index.js
  src/components/Search/SearchBar.js
  src/components/Search/SearchResults.js
  src/components/Section.js
  src/components/Showcase/StoryCard.js
  src/components/Showcase/StoryList.js
  src/components/Showcase/index.js
  src/components/Video/Player.js
  src/components/Video/Thumbnail.js
  src/components/Video/index.js
  src/pages/Resources.js
Labels: bug, enhancement

#41 Fix detect current user location + or browse list point to list on right.
  src/components/Modal/GetLocation.js
  src/components/Modal/PortalChooser.js
  src/lib/api.js
Labels: bug

#48 Fix embed page fonts
  src/pages/Embed.js
Labels: bug

#49 [Hotfix] Use yarn version for versioning releases
  .bumpversion.cfg
  package.json
Labels: bug, enhancement
