Repository CodeForAfrica/Dominion.AFRICA, pull requests merged in 2020-01, with the labels that each got.

#56 Add Featured Data to country landing page
  package.json
  src/components/FeaturedData/index.js
  src/data/featuredCharts.js
  src/lib/utils/customChartColorScale.js
  src/pages/[countrySlug].js
  yarn.lock
Labels: enhancement

#57 [HotFix] Chart source links update
  src/data/charts.json
Labels: bug

#59 Hide Kenya profile
  src/components/Footer/About.js
  src/config.js
  src/data/sources.sql
Labels: enhancement

#60 [Hotfix] Featured data chart container
  src/components/FeaturedData/index.js
  yarn.lock
Labels: bug, dependencies

#58 Skynet 🤖
  src/config.js
  src/pages/robots.txt.js
Labels: enhancement
